# Generated by Django 4.0.6 on 2022-08-10 18:16

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, unique=True, verbose_name='متن')),
                ('color', colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None, verbose_name='رنگ')),
                ('value', models.IntegerField(verbose_name='مقدار')),
                ('lucky_award', models.CharField(choices=[('پوچ', 'پوچ'), ('تخفیف', 'تخفیف'), ('شارژ کیف پول', 'شارژ کیف پول')], max_length=20, verbose_name='جایزه')),
            ],
            options={
                'verbose_name': 'جایزه',
                'verbose_name_plural': 'جایزه',
            },
        ),
        migrations.CreateModel(
            name='HideAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='مقدار')),
                ('lucky_award', models.CharField(choices=[('پوچ', 'پوچ'), ('تخفیف', 'تخفیف'), ('شارژ کیف پول', 'شارژ کیف پول')], max_length=20, verbose_name='جایزه')),
            ],
            options={
                'verbose_name': 'جایزه مخفی',
                'verbose_name_plural': 'جایزه های مخفی',
            },
        ),
        migrations.CreateModel(
            name='SpacialAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_number', models.IntegerField(verbose_name='شماره')),
                ('value', models.IntegerField(verbose_name='مقدار')),
                ('lucky_award', models.CharField(choices=[('پوچ', 'پوچ'), ('تخفیف', 'تخفیف'), ('شارژ کیف پول', 'شارژ کیف پول')], max_length=20, verbose_name='جایزه')),
            ],
            options={
                'verbose_name': 'جایزه ویژه',
                'verbose_name_plural': 'جایزه های ویژه',
            },
        ),
    ]
